name: Build macOS App

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
    inputs:
      publish_release:
        description: 'Publish a new release?'
        required: true
        type: boolean
        default: false


jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-13
            arch: x86_64
            display_name: macOS_Intel
          - os: macos-14
            arch: arm64
            display_name: macOS_ARM
          - os: ubuntu-latest
            arch: x86_64
            display_name: Linux_Intel
          - os: ubuntu-24.04-arm64
            arch: aarch64
            display_name: Linux_ARM

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Linux Dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y libfuse2 binutils
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Generate Obfuscated Config and Version
      env:
        SS_DEV_ID: ${{ secrets.SS_DEV_ID }}
        SS_DEVPASS: ${{ secrets.SS_DEVPASS }}
      run: |
        echo "${{ github.run_number }}" > version.txt
        python3 build_utils.py
        
    - name: Build macOS App
      if: startsWith(matrix.os, 'macos')
      run: |
        chmod +x build_app.sh
        ./build_app.sh
        cd dist
        zip -r "VPX_Manager_${{ matrix.display_name }}.zip" "VPX Manager for ES-DE.app"

    - name: Build Linux AppImage
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        chmod +x build_app.sh
        ./build_app.sh
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VPX_Manager_${{ matrix.display_name }}
        path: |
          dist/*.zip
          dist/*.AppImage
        
    - name: Create or Update Release
      if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || (github.event_name == 'workflow_dispatch' && inputs.publish_release == true)
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.zip
          dist/*.AppImage
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
